
# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool: 
  vmImage: ubuntu-latest 
  name: Default 

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '481b1dfa-09f6-4305-a978-b656e03d8e84'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Python version: 3.7
  pythonVersion: '3.7'

steps:
- script: echo Hello, world!
 displayName: 'Run a one-line script'

- script: |
   echo Add other tasks to build, test, and deploy your project.
   echo See https://aka.ms/yaml
 displayName: 'Run a multi-line script'